:images-dir: habilidades

=== Franco León Costantini
---
[.text-center.contact-table, grid=none, frame=none, stripes=none, %noheader]
|===
| Argentina, Buenos Aires, José C. Paz &#124; francoleonadress@gmail.com &#124; +54 11 5717-9268 &#124; link:https://francoleon42.github.io/portafolio/[Portafolio]
|===


**_Desarrollador de software_** +

Profesional de IT versátil con 2 años de experiencia en desarrollo full-stack y habilidades clave en optimización de código, desarrollo de APIs RESTful y aplicaciones móviles. Además de mis logros técnicos, he desarrollado una sólida capacidad de comunicación y enseñanza como docente de programación universitaria Busco un puesto de tiempo completo en una empresa que valore el aprendizaje continuo y donde pueda aportar valor con mis habilidades técnicas y de trabajo en equipo.

// La formacion es cuadro de dos columnas donde la primer va el titulo y en la otra la institucion y fecha
==== ***Formación Académica***

[grid=none, frame=none, cols="60,50"]
|===
| *Licenciatura en Sistemas* (70%)  
| [small]#**Universidad Nacional de General Sarmiento**, 2021-act#

| *Curso Fundamento Scrum CertiProf*  
| [small]#**CertiProf**, Enero 2023#

| *Desarrollador Web Full Stack* 
| [small]#**Egg Academy**, Diciembre 2022- May 2023#

| *Curso Productividad Personal*  
| [small]#**Google Active**, Diciembre 2022#
|===


// La experiencia profesional tiene un titulo en formato columna la primera es el titulo con su empresa y la otra el rango de fechas
// Debajo un listado de las tareas realizadas con orientacion a logros
==== ***Experiencia Profesional*** 

//
//[grid=none, frame=none, cols="90,20"]
//|===
//| **Desarrollador Backend – _Innovatech Solutions_**
//| [small]#_(Ene 2023- Sep 2024)_# 
//|===

//** Optimización y mantenimiento de aplicaciones web, mejorando el rendimiento y la eficiencia del sistema en un 20%.
//** Desarrollo y mantenimiento de APIs RESTful para integrar nuevos servicios y ampliar la funcionalidad de las aplicaciones.
//** Colaboración con equipos multidisciplinarios bajo metodologías ágiles, incrementando la eficiencia en el desarrollo de nuevas funcionalidades.

    
[grid=none, frame=none, cols="90,20"]
|===
| **Profesor de Programación – _Universidad Nacional General Sarmiento_** 
| [small]#_(Jun 2024 - actualidad)_#  
|===

** Impartí clases en Introducción a la Programación (2024) y Fundamentos de Programación (2025), ayudando a los estudiantes a comprender conceptos clave y desarrollar habilidades técnicas.
** Diseñé y coordiné actividades prácticas y evaluaciones, brindando orientación personalizada y retroalimentación constructiva para fortalecer el aprendizaje.


[grid=none, frame=none, cols="90,20"]
|===
| **Desarrollador de software – _Teset (Entidad Financiera)_**  
| [small]#_(Oct 2024- Dic 2025)_# 
|===

** Desarrollo de sistemas y aplicaciones para automatizar procesos internos y mejorar la experiencia de clientes.
** Implementación de soluciones tecnológicas que optimizan procesos administrativos y reducen errores operativos.
** Creación de aplicaciones móviles para clientes, facilitando el acceso a servicios financieros y aumentando la eficiencia del uso de los mismos.

[grid=none, frame=none, cols="90,20"]
|===
| **Desarrollador de software – _GRÚAS SAN BLAS S.A_** 
| [small right]#(Ene 2025 – Sep 2025)#
|===
** Mantenimiento y desarrollo de nuevas funcionalidades en el ERP de la empresa, incluyendo integración con módulos adicionales.
** Trabajo en equipo de 12 personas, participando en todas las etapas del ciclo de desarrollo. 
** Desarrollo backend en Java utilizando CUBA Platform, asegurando eficiencia y escalabilidad del sistema.
** Contribución a la optimización de procesos internos a través de soluciones de software.
 




